name: CI/CD Pipeline

on:
    push:
        tags:
            - "*"

jobs:
    release:
        name: Build and Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Extract tag name
              id: get-tag
              run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

            - name: Install Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.24

            - name: Update version in main.go
              run: |
                  TAG=${{ env.TAG }}
                  if [ -f main.go ]; then
                    sed -i 's/version_replaceme/'"$TAG"'/' main.go
                    echo "Updated main.go with version $TAG"
                  else
                    echo "main.go not found"
                  fi

            - name: Build binaries
              run: |
                  make go-build-release

            - name: Upload artifacts from /bin
              uses: actions/upload-artifact@v4
              with:
                  name: binaries
                  path: bin/
